In [4]:
import numpy as np
import time
np.random.seed(42)
print("NumPy version:",np.version.version)

NumPy version: 2.1.3


In [10]:
prices =list(range(1,1000001))

start =time.time()
discounted_loop=[p*0.95 for p in prices]
loop_time=time.time() - start
print(f"loop version:{loop_time:.4f} seconds")

prices_np =np.arange(1,1000001)
discounted_loop=[prices_np*0.95]
np_time=time.time() - start
print(f"Numpy version:{np_time:.4f} seconds")
print(f"Numpy was about{loop_time/np_time:.0f}%faster")

loop version:0.2610 seconds
Numpy version:0.3203 seconds
Numpy was about1%faster


In [13]:
#creating arrays


a = np.array([10,20,30,40])
zeros=np.zeros((2,3))
ones=np.ones((3,3))
seq=np.arange(0,10,3)
lin=np.linspace(0,1,5)

print("a:",a)
print("zeros:\n",zeros)
print("ones:\n",ones)
print("seq:",seq)
print("lin:",lin)


a: [10 20 30 40]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
seq: [0 3 6 9]
lin: [0.   0.25 0.5  0.75 1.  ]
